FROM debian:bullseye

RUN apt-get update && apt upgrade -y && \
	apt-get install -y \
	mariadb-server

COPY conf/50-server.cnf /etc/mysql/mariadb.conf.d/50-server.cnf

RUN mkdir -p /var/run/mysqld \
	&& chown -R mysql:mysql /var/run/mysqld \
	&& chmod 777 /var/run/mysqld

#EXPOSE 3306

COPY ./tools/mdb.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/mdb.sh

RUN mysql_install_db

ENTRYPOINT [ "/usr/local/bin/mdb.sh" ]
